(set-language-environment "UTF-8")
(setq standard-indent 4)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 4)
(global-set-key (kbd "RET") 'newline-and-indent)
(setq make-backup-files nil)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq ring-bell-function 'ignore)
(setq display-time-24hr-format t)
(display-time-mode t)
(setq display-time-day-and-date 1)
(require 'whitespace)
(setq whitespace-style '(face lines-tail))
(global-whitespace-mode t)
